config/routes.rb
Rails.application.routes.draw do
  resources :cabinets do 
    post :new, on: :member
  end
  resources :ingredients

  resources :recipes do
    post :favorite, on: :member
    get :favorites, on: :collection
    patch :move_step, on: :member
  end

  # authentication routes
  devise_for :users, controllers: { sessions: 'users/sessions', 
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'}
  devise_scope :user do 
    #reroutes users to sign-in after sign-out
    get "users", to: "users/sessions#new"
    get 'users/sign_out', to: 'users/sessions#destroy'
  end

  # Defines the root path route ("/")
  root 'recipes#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  before_validation :generate_slug

  include Portionable
  
  has_one_attached :image
  has_and_belongs_to_many :users
  has_and_belongs_to_many :tools
  has_and_belongs_to_many :categories
  has_many :ingredients, through: :portions
  has_many :steps, dependent: :destroy
  has_many :favorite_recipes
  has_many :favorited_by, through: :favorite_recipes, source: :user

  accepts_nested_attributes_for :steps, allow_destroy: true
  accepts_nested_attributes_for :categories_recipes, allow_destroy: false
  accepts_nested_attributes_for :portions, allow_destroy: true, reject_if: proc { |att| att['ingredient_id'].blank? }

  validates :name, presence: true
  validates :slug, uniqueness: true, presence: true

  # ordering scopes
  scope :alphabetical, -> { order(:name) }

  # filtering scopes
  scope :search, lambda{ |search_term| self.where('recipes.name ILIKE ?', "%#{ search_term }%").distinct if search_term.present? }
  scope :by_category, lambda{ |category_ids| self.joins(:categories).where(categories: { id: category_ids }) if category_ids.present? }
  scope :by_all_ingredients, lambda{ |ingredient_ids| self.joins(:ingredients).group(:id).having('array_agg(ingredients.id) @> ?', ingredient_ids) if ingredient_ids.present? }
  scope :by_any_ingredient, lambda{ |ingredient_ids| self.joins(:ingredients).where(ingredients: { id: ingredient_ids }).distinct }
  scope :user_has_all_ingredients, lambda{ |user_ingredients| self.joins(:ingredients).group(:id).having('array_agg(ingredients.id) <@ ?', user_ingredients) if user_ingredients.present? }

  def to_param
    slug
  end

  def generate_slug
    self.slug ||= name.parameterize
  end

  def self.search_recipes(search_params, user)
    sort_option = search_params[:sortOption]
    category_ids = search_params[:categoryIds]
    search_term = search_params[:searchTerm]

    # needed to cast these into Postgres array format in order to function properly
    ingredient_ids = '{' + search_params[:ingredientIds].join(', ') + '}' if search_params[:ingredientIds]
    user_ingredients = '{' + user.ingredients.join(', ') + '}'

    case sort_option
    when 'All Recipes'
      by_category(category_ids)
        .by_all_ingredients(ingredient_ids)
        .search(search_term)
    when 'I Have Any Ingredient' 
      by_category(category_ids)
        .by_any_ingredient(user.ingredients)
        .by_all_ingredients(ingredient_ids)
        .search(search_term)
    when 'I Have All Ingredients'
      by_category(category_ids)
        .user_has_all_ingredients(user_ingredients)
        .by_all_ingredients(ingredient_ids)
        .search(search_term)
    when 'Favorites'
      user.favorites
        .by_category(category_ids)
        .by_all_ingredients(ingredient_ids)
        .search(search_term)
    when 'My Recipes'
      user.recipes
        .by_category(category_ids)
        .by_all_ingredients(ingredient_ids)
        .search(search_term)
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # handles favoriting/unfavoriting
  # POST /recipes/1/favorite
  def favorite
    set_recipe
    if current_user.favorites.include?(@recipe)
      current_user.favorites.delete(@recipe)
      render partial: 'components/favoriting/unfavorite', locals: { recipe: @recipe }
    else
      current_user.favorites << @recipe
      render partial: 'components/favoriting/favorite', locals: { recipe: @recipe }
    end
  end

  def move_step
    if set_step
      @step.insert_at(params[:position].to_i)
    end
  end

  # GET /recipes or /recipes.json
  def index
    @home = true
    @page = params[:page] || 1
    
    @recipes = Recipe.with_attached_image
                .all
                .alphabetical
                .page(@page)
                
    @recipe_count = @recipes.total_count

    if params[:search]
      @recipes = Recipe.search_recipes(
                          params[:search],
                          current_user
                        )
                        .alphabetical
                        .with_attached_image
                        .all
                        .page(@page)
      @recipe_count = @recipes.total_count

        respond_to do |format|
          format.html { render partial: 'components/recipe_cards/recipe_cards_container', formats: [:html] }
          format.turbo_stream
        end
    end
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @recipe.steps.build
    @recipe.portions.build
  end

  # GET /recipes/1/edit
  def edit
    @edit = true
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    respond_to do |format|
      begin 
        @recipe.save!
        @recipe.users << current_user
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      rescue ActiveRecord::RecordNotUnique => e
        flash[:error] = "Recipe name already in use"
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      rescue => e
        flash[:error] = e.message
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      # process_portions method explained in application_controller.rb
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.portions.destroy_all
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_step
      @step = Step.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find_by_slug!(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      # need to explicitly include :id for :steps/:portions for :_destroy to work
      params.require(:recipe).permit(
        :name, 
        :description, 
        :image, 
        category_ids: [], 
        tool_ids: [],                           
        steps_attributes: [
          :id,
          :ingredient_id,
          :name,
          :description,
          :position,
          :_destroy
        ],
        portions_attributes: [
          :id,
          :ingredient_id,
          :amount,
          :unit,
          :portionable_type,
          :portionable_id,
          :optional,
          :_destroy
        ]
      )                      
    end
end

app/views/recipes/_favoriting_widget.html.erb
<div role='button' 
     class='favoriting-widget position-absolute m-2' 
     data-url='<%= favorite_recipe_path(recipe) %>' 
     data-controller='recipes' 
     data-action='click->recipes#favorite' >
  
  <% if current_user.favorites.include?(recipe) %>
    <%= render partial: 'favorite' %>
  <% else %>
    <%= render partial: 'unfavorite' %>
  <% end %>
</div>

app/views/recipes/_form.html.erb
 <div id='recipe-form' data-controller='recipes' class='w-50 fs-6 fw-bold'> 
  <%# recipe form using simple_form/cocoon gems %>
  <%= simple_form_for @recipe do |f| %>
    <%= f.error_notification %>

    <%# recipe inputs %>
    <div class='row'>
      <div class='form-inputs'>
        <%= f.input :name, required: true, input_html: {class: 'w-50'} %>
        <%= f.input :description, input_html: {class: 'w-100'} %>
      </div>
    </div>

    <%# recipe categories %>
    <div class='row'>
      <div>
        <%= f.collection_check_boxes :category_ids, 
                                     Category.all.order(:name), 
                                     :id, 
                                     :name, 
                                     include_hidden: false %>
      </div>
    </div>

    <%# recipe ingredients %>
    <div class='row'>
      <%= render partial: 'portion_table', locals: { f: f } %>
    </div>

    <%# recipe steps %>
    <div class='row'>
      <%= render partial: 'step_table', locals: { f: f } %>
    </div>
    
    <%# add image %>
    <div class='row my-2'>
      <div class='text-center'>

        <%# wrapping file_field in a label to style the attach button %>
        <label class='btn btn-sm btn-outline-dark'>
          <%= @recipe.id ? 'Edit Image' : 'Add Image' %>
          <span class='d-none'><%= f.file_field :image, id: 'add-image-btn' %></span>
        </label>

        <%# image filename inserted via jquery after upload%>
        <p id='img-file-name' class='fst-italic fw-normal mt-2 text-danger'></p>
      </div>
    </div>

    <%# form submit %>
    <div class='row'>
      <div class='text-center'>
        <%= f.button :submit, class: 'btn-sm btn-success' %>
      </div>
    </div> 
  <% end %>
</div>

app/views/recipes/_recipe-card.html.erb
<div class="col">
  <div class="card" style="width: 15rem;">

    <%# favoriting widget %>
    <%= render partial: 'favoriting_widget', locals: { recipe: recipe } %>

    <%# if custom image not added, adds default image %>
    <% if recipe.image.present? %>
      <%= image_tag recipe.image, class: ""  %>
    <% else %>
      <img src=<%= asset_path('default.webp') %> class="">
    <% end %>

    <%# displays cocktail name and snippet of description %>
    <div class="card-body">
      <h5 class="card-title"><%= link_to recipe.name, recipe, class: 'text-decoration-none text-dark' %></h5>
      <p class="card-text h-75 text-truncate"><%= recipe.description %></p>
    </div>
    
  </div>
</div>

app/views/recipes/_recipe.html.erb
<div id='recipe-details-container'>
  <div class='row'>

    <div class='col-auto'>
      <div>
        <%= render partial: 'components/favoriting/favoriting_widget', locals: { recipe: recipe } %>
        
        <% if recipe.image.present? %>
          <%= image_tag recipe.image, class: "recipe-image"  %>
        <% else %>
          <img src=<%= asset_path('default.webp') %> class='recipe-image'>
        <% end %>
      </div>
    </div>


    <div class='col'>
      
      <div class='recipe-show-header'>
        <div class='show-header'>
          <h2 class='show-header'><%= @recipe.name.titleize %></h2>
        </div>
        <div class='edit-btn'>
          <a href='<%= edit_recipe_path(@recipe) %>'>
            <i class="fa-solid fa-pencil"></i>
          </a>
        </div>
      </div>


      <div class='row'>
        <div class='col-4'>

          <%# ingredients list %>
          <div class='recipe-details-container'>
            <div class='recipe-details-header'>Ingredients</div>
            <ul class='recipe-details-list'>
              <% recipe.portions.each do | portion | %>
                <li class='recipe-details-list-item'>
                  <% if Cabinet.find(current_user.default_cabinet).ingredients.include?(portion.ingredient) %>
                    <span>&check;</span>
                  <% else %>
                    <span>˟</span>
                  <% end %>
                  <%= [ portion.ingredient.display_name, portion.amount, portion.unit ].join(' ') %>
                </li>
              <% end%>
            </ul>
          </div>

          <%# tools display %>
          <% unless recipe.tools.empty? %>
            <div class='recipe-details-container'>
              <div class='recipe-details-header'>Tools</div>
              <ul class='recipe-details-list'>
                <% recipe.tools.each do | tool | %>
                  <li>
                    <% if Cabinet.find(current_user.default_cabinet).tools.include?(tool) %>
                      <span>&check;</span>
                    <% else %>
                      <span>˟</span>
                    <% end %>
                    <%= tool.tool_type %>
                  </li>
                <% end%>
              </ul>
            </div>
          <% end %>
        </div>
        
        <div class='col'>
          <%# recipe steps %>
          <div class='recipe-details-container'>
            <div class='recipe-details-header'>Steps</div>
            <ol class=''>
              <% recipe.steps.order(position: :asc).each do |s| %>
                <li><%= s.name %></li>
                <p><%= s.description %></p>
              <% end %>
            </ol>
          </div>

          <%# cocktail description (if any) %>
          <div class='recipe-details-container'>
            <% if recipe.description != "" %>
              <div class='recipe-details-header'>Description</div>
              <p><%= recipe.description %></p>   
            <% end%>
          </div> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/_recipe_card.html.erb
<div class='card-container'>
  
    <div class="card" data-value='<%= recipe.id %>'>

      <%# favoriting widget %>
      <%= render partial: 'favoriting_widget', locals: { recipe: recipe } %>
      
      <a href='<%= recipe_path(recipe) %>'>
        <%# if custom image not added, adds default image %>
        <div class='card-img-container'>
          <% if recipe.image.present? %>
            <%= image_tag recipe.image, class: "card-img"  %>
          <% else %>
            <img src=<%= asset_path('default.webp') %> class="card-img">
          <% end %>
        </div>

        <%# displays cocktail name and snippet of description %>
        <div class="card-body">
          <h5 class="card-title"><%= recipe.name %></h5>
          <p class="card-text h-75 text-truncate"><%= recipe.description %></p>
        </div>
       </a>
    </div>
 
</div>

app/views/recipes/_recipe_cards.html.erb
<div class="container-fluid mt-2 mx-3">
  
  <div 
    id="recipes" 
    class="row row-cols-lg-5 row-cols-md-4 row-cols-sm-3 g-2" 
    data-controller='recipes'
    data-action='load->recipes#updateRecipeCount'
    data-value=<%= @recipe_count %>
  >
    <% @recipes.each do |recipe| %>
      <%= render partial: "recipe_card", locals: { recipe: recipe } %>
    <% end %>

    <% if @recipes.empty? %>
      <div class='text-light bg-dark'>No recipes found matching your criteria...</div>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class='container'>
  
  <div class='row'>
    <div class='d-flex justify-content-center'>
      <%= render "components/recipe_form/form", locals: { recipe: @recipe, edit: @edit } %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<%# main content %>
<div class='bg-img main-content-wrapper'>
  
  <%# anchor for recipe modal %>
  <div id='recipe-modal-container'></div>

  <div class='row'>
    <%= render partial: 'components/sort_tabs/sort_tabs' %>
  </div>

  <%# main page content %>
  <div class='row flex-nowrap'>
    
    <%# liquor cabinet sidebar %>
    <div class='liquor-cabinet-display col-2' data-controller='cabinets'>
      <%= render partial: 'components/cabinet_sidebar/cabinet_sidebar' %>
    </div>

    <%# cocktail card container %>
    <div class='col offset-2 recipe-cards me-3' 
         data-controller='pagination'
         data-pagination-target='recipes'
         data-pagination-url-value='<%= recipes_url %>'
         data-pagination-page-value='<%= 2 %>'>

      <%= render partial: 'components/recipe_cards/recipe_cards_container', locals: { recipes: @recipes } %>
    </div>
  </div>
</div>

app/views/recipes/index.turbo_stream.erb
<%# appends next page of recipes to target element %>
<%= turbo_stream.append 'recipes' do %>
  <% @recipes.each do |recipe| %>
    <%= render partial: "components/recipe_cards/recipe_card", locals: { recipe: recipe } %>
  <% end %>

  <% if @recipes.page(@page.to_i + 1).out_of_range? %>
    <div class='hidden' data-pagination-target='noRecords'></div>
  <% end %>
<% end %>

app/views/recipes/new.html.erb
<div>
  <%= render "components/recipe_form/form", recipe: @recipe %>
</div>

app/views/recipes/show.html.erb
  <div id='show-content-container' class='container'>
    <div class='row'>
      <div id='recipe-show-container'>
        <%= render @recipe %>
      </div>
    </div>
</div>

app/views/recipes/show.js.erb
$('#recipe-modal-container').html("<%= j render 'components/recipe_modal/recipe_modal', recipe: @recipe %>");
$('#recipe-modal').modal('show');