config/routes.rb
Rails.application.routes.draw do
  resources :cabinets do 
    post :new, on: :member
  end
  resources :ingredients

  resources :recipes do
    post :favorite, on: :member
    get :favorites, on: :collection
    patch :move_step, on: :member
  end

  # authentication routes
  devise_for :users, controllers: { sessions: 'users/sessions', 
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'}
  devise_scope :user do 
    #reroutes users to sign-in after sign-out
    get "users", to: "users/sessions#new"
    get 'users/sign_out', to: 'users/sessions#destroy'
  end

  # Defines the root path route ("/")
  root 'recipes#index'
end

app/models/cabinet.rb
class Cabinet < ApplicationRecord
  before_validation :generate_slug

  include Portionable
  belongs_to :user, optional: true
  has_and_belongs_to_many :tools
  has_many :ingredients, through: :portions

  validates :name, presence: true 
  validates :slug, uniqueness: true, presence: true

  accepts_nested_attributes_for :portions, allow_destroy: true, reject_if: proc { |att| att['ingredient_id'].blank? }

  def to_param
    slug
  end

  def generate_slug
    self.slug ||= name.parameterize
  end
end

app/controllers/cabinets_controller.rb
class CabinetsController < ApplicationController
  before_action :set_cabinet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /cabinets or /cabinets.json
  def index
    @cabinets = Cabinet.where(user_id: current_user.id)
  end

  # GET /cabinets/1 or /cabinets/1.json
  def show
    @show = true
    # updates user's default cabinet when 
    # switching liquor cabinets in the sidebar and
    # re-renders the sidebar with new cabinet
    if params[:update_id]
      current_user.update!(default_cabinet: params[:update_id])
      @cabinet = Cabinet.find(params[:update_id])
      render partial: 'components/cabinet_sidebar/cabinet_sidebar', locals: { cabinet: @cabinet }
    end

    if params[:updateMobileMenu]
      render partial: 'components/cabinet_sidebar/cabinet_ingredients'
    end
  end

  # GET /cabinets/new
  def new
    # obtains ingredient type and returns it in a json for new cabinet form
    if params[:ingredientId]
      @ingredientType = Ingredient.find(params[:ingredientId]).type
      respond_to do |format|
        format.json { render json: { ingredientType: @ingredientType }}
      end
    end
    @cabinet = Cabinet.new
    @cabinet.portions.build
  end

  # GET /cabinets/1/edit
  def edit
    set_cabinet
    @cabinet.portions.build
    @edit = true
  end

  # POST /cabinets or /cabinets.json
  def create
    @cabinet = Cabinet.new(cabinet_params)

    respond_to do |format|
      if @cabinet.save
        format.html { redirect_to cabinet_url(@cabinet), notice: "Cabinet was successfully created." }
        format.json { render :show, status: :created, location: @cabinet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cabinet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabinets/1 or /cabinets/1.json
  def update
    respond_to do |format|
      if @cabinet.update(cabinet_params)
        format.html { redirect_to cabinet_url(@cabinet), notice: "Cabinet was successfully updated." }
        format.json { render :show, status: :ok, location: @cabinet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cabinet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabinets/1 or /cabinets/1.json
  def destroy
    @cabinet.destroy

    respond_to do |format|
      format.html { redirect_to cabinets_url, notice: "Cabinet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cabinet
      @cabinet = Cabinet.find_by_slug!(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cabinet_params
      params.require(:cabinet).permit(:name, 
                                      :locked, 
                                      :user_id, 
                                      tool_ids: [],
                                      portions_attributes: [:id,
                                                            :ingredient_id,
                                                            :amount,
                                                            :unit,
                                                            :portionable_type,
                                                            :portionable_id,
                                                            :_destroy])
    end
end

app/views/cabinets/_cabinet.html.erb
<div id="<%= dom_id cabinet %>">

  <div class='container'>
  
    <%# cabinet name %>
    <div class='recipe-show-header cabinet-header'>
      <div class='show-header'>
        <h2 class='cabinet-name'>
          <% if @show %>
            <%= cabinet.name %>
          <% else %>
            <a href='<%= cabinet_path(cabinet) %>'>
              <%= cabinet.name %>
            </a>
          <% end %>
        </h2>
      </div>
      <div class='edit-btn'>
        <% if @cabinet %>
          <a href='<%= edit_cabinet_path(@cabinet) %>'>
            <i class="fa-solid fa-pencil"></i>
          </a>
        <% end %>
      </div>
    </div>
    
    <%# ingredient columns %>
    <div class='row cabinet-display'>
      <% ['Spirit', 'Modifier', 'Sugar', 'Garnish'].each do |ingredient_type| %>
        <div class='col'>
          <h5 class='ingredient-header'>
            <%= ingredient_type.pluralize %>
          </h5>

          <div class='ingredient-container'>
            <% cabinet.portions.each do |portion| %>
              <% if portion.ingredient.class.to_s === ingredient_type %>
                <div class='cabinet-display-item'>
                  <%= [portion.ingredient.display_name, portion.amount, portion.unit].join(' ') %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>

      <%# tools column %>
      <div class='col'>
        <h5 class='ingredient-header'>Tools</h5>
        <div class='ingredient-container'>
          <% unless cabinet.tools.empty? %>
            <% cabinet.tools.each do | tool | %>
              <div class='cabinet-display-item'>
                <%= tool.tool_type %>
              </div>
            <% end%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cabinets/_form.html.erb
<div id='cabinet-form' class='w-50 fs-6 fw-bold'>
  <%= simple_form_for(@cabinet) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    
    <div class='row'>
      <div class="form-inputs">
        <%= f.hidden_field :user_id, value: current_user.id  %>
        <%= f.input :name, label: 'Name Your Liquor Cabinet' %>
      </div>
    </div>

    <div class='row'>
      <%= render partial: 'portion_table', locals: { f: f } %>
    </div>

    <div class='row'>
      <div class="form-actions">
        <%= f.button :submit, class: 'btn-sm btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/cabinets/edit.html.erb
<div class='mobile-page'>
  <%= render "components/cabinet_form/form", cabinet: @cabinet %>
</div>

app/views/cabinets/index.html.erb
<div id="cabinets" class='mobile-page'>
  <% @cabinets.each do |cabinet| %>
    <div class='cabinet-container'>
      <%= render cabinet %>
    </div>
  <% end %>
</div>

app/views/cabinets/new.html.erb
<div class='container'>
  <%= render "components/cabinet_form/form", cabinet: @cabinet %>
</div>

app/views/cabinets/show.html.erb
<div class='mobile-page'>
  <%= render @cabinet %>

  <div class='row my-5'>
    <div class='d-flex justify-content-center'>
      <%= button_to "Delete", @cabinet, method: :delete, class: 'btn btn-sm btn-dark' %>
    </div>
  </div>
</div>